version: '3'
services:
  nats:
    image: nats:2.6.4-alpine
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    profiles:
      - app

  postgresd:
    restart: unless-stopped
    build:
      context: ./docker/postgresd
    image: microlobby-postgresd:latest
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgresd:/var/lib/postgresql/data:cached
    profiles:
      - app

  pgadmin:
    restart: unless-stopped
    image: docker.io/dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8086:80
    depends_on:
      - postgresd
    volumes:
      - pgadmin:/var/lib/pgadmin
    profiles:
      - app

  http_proxy:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/genericservice/Dockerfile
      args:
        SERVICE: http_proxy
    image: microlobby-service-http_proxy:latest
    environment:
      - MICRO_SERVER_ADDRESS=0.0.0.0:8080
      - MICRO_TRANSPORT=nats
      - MICRO_TRANSPORT_ADDRESS=nats:4222
      - MICRO_REGISTRY=nats
      - MICRO_REGISTRY_ADDRESS=nats:4222
      - MICRO_BROKER=nats
      - MICRO_BROKER_ADDRESS=nats:4222
    ports:
      - 8080:8080
    depends_on:
      - nats
      - postgresd
    profiles:
      - app

  lobby_v1:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/genericservice/Dockerfile
      args:
        SERVICE: lobby/v1
    image: microlobby-service-lobby-v1:latest
    environment:
      - MICRO_TRANSPORT=nats
      - MICRO_TRANSPORT_ADDRESS=nats:4222
      - MICRO_REGISTRY=nats
      - MICRO_REGISTRY_ADDRESS=nats:4222
      - MICRO_BROKER=nats
      - MICRO_BROKER_ADDRESS=nats:4222
    depends_on:
      - nats
      - postgresd
    profiles:
      - app

  auth_v1:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/genericservice/Dockerfile
      args:
        SERVICE: auth/v1
    image: microlobby-service-auth-v1:latest
    environment:
      - MICRO_TRANSPORT=nats
      - MICRO_TRANSPORT_ADDRESS=nats:4222
      - MICRO_REGISTRY=nats
      - MICRO_REGISTRY_ADDRESS=nats:4222
      - MICRO_BROKER=nats
      - MICRO_BROKER_ADDRESS=nats:4222
      - DATABASE_DEBUG=true
      - DATABASE_URL=${ML_AUTH_DB_URL}
    depends_on:
      - nats
      - postgresd
    profiles:
      - app

  settings_v1:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/genericservice/Dockerfile
      args:
        SERVICE: settings/v1
    image: microlobby-service-settings-v1:latest
    environment:
      - MICRO_TRANSPORT=nats
      - MICRO_TRANSPORT_ADDRESS=nats:4222
      - MICRO_REGISTRY=nats
      - MICRO_REGISTRY_ADDRESS=nats:4222
      - MICRO_BROKER=nats
      - MICRO_BROKER_ADDRESS=nats:4222
      - DATABASE_DEBUG=true
      - DATABASE_URL=${ML_SETTINGS_DB_URL}
    depends_on:
      - nats
      - postgresd
    profiles:
      - app

  builder:
    restart: "no"
    build:
      context: ./docker/builder
    image: microlobby-builder:latest
    environment:
      - GOPROXY=https://proxy.golang.org,direct
    volumes:
      - "~/go:/go:rw"
      - ".:/microlobby:rw"
    profiles:
      - tools

volumes:
  postgresd: {}
  pgadmin: {}
