version: '3'

dotenv: [".env"]

vars:
  CMD_PODMAN:
    sh: command -v podman
  CMD_DOCKER:
    sh: command -v docker
  CMD_DCOMPOSE:
    sh: command -v docker-compose

tasks:
  default:
    desc: Build and run microlobby
    env:
      # For service:protoc
      SERVICE: 
        var: {{.SERVICES}}
    cmds:
      - task: sysctl
      - task: build:tools
      - task: service:protoc
      - task: build
      - task: up

  sysctl:
    desc: Run sysctl to allow <=80 ports
    deps:
      - check:toolchain
    cmds:
      - |
        # Run for podman
        test -z "{{.CMD_PODMAN}}" && exit 0
        sudo sysctl net.ipv4.ip_unprivileged_port_start=80

  build:
    desc: Build all containers
    deps:
      - check:toolchain
    cmds:
      - |
        # Run with podman
        test -z "{{.CMD_PODMAN}}" && exit 0
        for svc in {{.SERVICES}}; do 
          podman build -v "{{.GOPATH}}:/go:rw" -t localhost/microlobby-service-$(echo ${svc} | sed 's#/#-#g'):latest --build-arg=SERVICE=${svc} -f docker/genericservice/Dockerfile . || exit 1
        done
      - | 
        # Run with docker
        test -n "{{.CMD_PODMAN}}" && exit 0
        docker-compose --profile app build

  build:protoc-gen-micro:
    run: once
    cmds:
    - |
      # Run with podman
      test -z "{{.CMD_PODMAN}}" && exit 0
      test -f "{{.GOPATH}}/bin/protoc-gen-micro" && exit 0
      podman run --rm -v "{{.GOPATH}}:/go:rw" -v ".:/microlobby:rw" localhost/microlobby-builder go install go-micro.dev/v4/cmd/protoc-gen-micro@v4 || exit 1
    - | 
      # Run with docker
      test -n "{{.CMD_PODMAN}}" && exit 0
      test -f "{{.GOPATH}}/bin/protoc-gen-micro" && exit 0
      docker-compose --profile tools run --rm builder go install go-micro.dev/v4/cmd/protoc-gen-micro@v4

  build:tools:
    desc: Build tools
    deps:
     - check:toolchain
    cmds:
      - docker-compose --profile tools build
      - task: build:protoc-gen-micro

  buildup:
    desc: Run this when you changed something
    cmds:
      - task: build
      - task: up

  service:build:
    desc: Build a specific service using env var "SERVICE"
    deps:
      - check:toolchain
    cmds:
      - |
        # Run with podman
        test -z "{{.CMD_PODMAN}}" && exit 0
        test -n "{{.SERVICE}}" -a -d service/{{.SERVICE}} || exit 123
        podman build -v "{{.GOPATH}}:/go:rw" -t localhost/microlobby-service-$(echo {{.SERVICE}} | sed 's#/#-#g'):latest --build-arg=SERVICE={{.SERVICE}} -f docker/genericservice/Dockerfile . || exit 1
      - | 
        # Run with docker
        test -n "{{.CMD_PODMAN}}" && exit 0
        test -n "{{.SERVICE}}" -a -d service/{{.SERVICE}} || exit 123
        docker-compose --profile app build {{.SERVICE}}

  service:buildrun:
    desc: Build and run a service using env var "SERVICE"
    deps:
      - check:toolchain
    cmds:
      - task: service:build
      - task: up

  service:http_proxy:
    desc: Build and run/restart http_proxy
    cmds:
      - task: service:build
        vars:
          SERVICE: http_proxy
      - task: up

  service:auth_v1:
    desc: Build and run/restart auth/v1, restart http_proxy
    cmds:
      - task: service:build
        vars:
          SERVICE: auth/v1
      - task: up
      - docker-compose stop http_proxy; docker-compose start http_proxy

  service:settings_v1:
    desc: Build and run/restart settings/v1, restart http_proxy
    cmds:
      - task: service:build
        vars:
          SERVICE: settings/v1
      - task: up
      - docker-compose stop http_proxy; docker-compose start http_proxy

  service:protoc:
    desc: Generate shared protobuf files and those for a service
    deps:
      - check:toolchain
    cmds:
      - |
        # Run with podman
        test -n "{{.CMD_PODMAN}}" && \
        podman run --rm -v "{{.GOPATH}}:/go:rw" -v ".:/microlobby:rw" localhost/microlobby-builder /scripts/protogen.sh "{{.SERVICE}}"

      - | 
        # Run with docker
        test -n "{{.CMD_PODMAN}}" || \
        docker-compose --profile tools run --rm builder /scripts/protogen.sh "{{.SERVICE}}"

  up:
    desc: Run all containers
    deps:
      - check:toolchain
    cmds:
      - docker-compose --profile app up -d --remove-orphans
      - docker-compose ps
      
  down:
    desc: Stopp all containers
    deps:
      - check:toolchain
    cmds:
      - docker-compose --profile app down

  download:
    desc: Download go dependencies
    deps:
      - check:toolchain
    cmds:
      - |
        # Run with podman
        test -n "{{.CMD_PODMAN}}" && \
        podman run --rm -v "{{.GOPATH}}:/go:rw" -v ".:/microlobby:rw" localhost/microlobby-builder sh -c "cd /microlobby && go mod download"

      - | 
        # Run with docker
        test -n "{{.CMD_PODMAN}}" || \
        docker-compose --profile tools run --rm builder sh -c "go mod download"
  
  upgrade:deps:
    desc: Update all go dependencies
    deps:
      - check:toolchain
    cmds:
      - |
        # Run with podman
        test -n "{{.CMD_PODMAN}}" && \
        podman run --rm -v "{{.GOPATH}}:/go:rw" -v ".:/microlobby:rw" localhost/microlobby-builder /scripts/upgrade_deps.sh "{{.SERVICES}}"

      - | 
        # Run with docker
        test -n "{{.CMD_PODMAN}}" || \
        docker-compose --profile tools run --rm builder /scripts/upgrade_deps.sh "{{.SERVICES}}"

  check:toolchain:
    run: once
    desc: Check if you have all tools installed
    cmds:
      - test -n "{{.CMD_PODMAN}}" -o -n "{{.CMD_DOCKER}}"
      - test -n "{{.CMD_DCOMPOSE}}"
      - test ! -d "{{.GOPATH}}" && mkdir "{{.GOPATH}}" || exit 0
